spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plt?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    request-context-attribute: req
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    charset: UTF-8
    settings:
      number_format: '0.##'
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8111